export const LOCAL_IDENTITIES_KEY = 'lm-talk-local-identities-v1'

export const MAX_TEXT_MESSAGE_BYTES = 64 * 1024
export const MAX_CONTACT_CARD_BYTES = 32 * 1024
export const MAX_SIGNAL_BYTES = 256 * 1024
export const MAX_FILE_BYTES = 16 * 1024 * 1024
export const MAX_RTC_TEXT_BYTES = MAX_FILE_BYTES * 3
export const MAX_PROFILE_AVATAR_BYTES = 64 * 1024
export const PROFILE_AVATAR_DIMENSION = 128
export const FILE_BASE64_CHUNK_BYTES = 3 * 256 * 1024

export const FRIEND_REQUEST_RATE_WINDOW_MS = 10 * 60 * 1000
export const FRIEND_REQUEST_RATE_LIMIT = 3
export const FRIEND_REQUEST_LONG_RATE_WINDOW_MS = 24 * 60 * 60 * 1000
export const FRIEND_REQUEST_LONG_RATE_LIMIT = 5

export const MAILBOX_DEDUPE_MAX_RECORDS = 1000
export const MAILBOX_DEDUPE_RETENTION_MS = 30 * 24 * 60 * 60 * 1000
export const MAILBOX_LONG_POLL_WAIT_SECONDS = 25
export const MAILBOX_LONG_POLL_TIMEOUT_MS = 35_000
export const MAILBOX_HINT_BACKGROUND_REFRESH_DELAY_MS = 5_000

export const DHT_OPERATION_HISTORY_MAX_RECORDS = 8
export const DHT_OPERATION_HISTORY_IMPORT_MAX_RECORDS = 32
export const DHT_OPERATION_HISTORY_ITEM_MAX_CHARS = 240

export const MAX_OUTBOX_RETRY_COUNT = 5
export const SECURE_SESSION_RECOVERY_COOLDOWN_MS = 60_000
export const NODE_FETCH_TIMEOUT_MS = 10_000
export const PERSIST_DEBOUNCE_MS = 120

export const CONTACT_CARD_UPDATE_ACK_STALE_MS = 24 * 60 * 60 * 1000
export const CONTACT_CARD_DHT_FRESH_MS = 7 * 24 * 60 * 60 * 1000

export const GROUP_EVENT_PAYLOAD_PREFIX = 'lm-group-event-message-v1:'
export const GROUP_SENDER_KEY_PAYLOAD_PREFIX = 'lm-group-sender-key-message-v1:'
